openapi: 3.0.0
info:
  title: exchange_rates
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /exchange_rates/short:
    get:
      summary: Курсы валют (виджет)
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        currency:
                          $ref: '#/components/schemas/Currency'
                        rate:
                          type: number
                          description: Текущий курс
                        previous_rates:
                          type: array
                          description: Курсы за прошлые дни
                          items:
                            type: object
                            properties:
                              date:
                                type: number
                              rate:
                                type: number
        '':
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type:
                      - string
                      - array
                    items:
                      type: object
                      properties:
                        '':
                          type: string
      operationId: get-exchange_rates
      description: Получение краткого описания основных курсов валют
    parameters: []
  /exchange_rates:
    get:
      summary: Курсы валют
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: number
                        currency:
                          $ref: '#/components/schemas/Currency'
                        multiplier:
                          type: number
                          description: Коэффициент
                        rate:
                          type: number
                          description: Курс
                  meta:
                    $ref: '#/components/schemas/PaginationMeta'
      operationId: get-exchange_rates
      description: Получение информации о курсах валют
      parameters:
        - schema:
            type: string
          in: query
          name: currency
          description: Валюта
        - schema:
            type: string
          in: query
          name: date_start
          required: true
          description: Дата начала
        - schema:
            type: string
          in: query
          name: date_end
          description: Дата окончания
        - schema:
            type: string
          in: query
          name: page
          description: Страница
        - schema:
            type: string
          in: query
          name: page_size
          description: Размер страницы
components:
  schemas:
    PaginationMeta:
      title: PaginationMeta
      type: object
      description: ''
      properties:
        objects_count:
          type: integer
          description: 'Количество элементов, полученных в ответе'
        objects_total:
          type: number
          description: Всего элементов
        pages_count:
          type: integer
          description: Всего страниц
        page_number:
          type: integer
          description: Номер страницы
    Currency:
      title: Currency
      type: object
      properties:
        code:
          type: string
          description: Код
        name:
          type: string
          description: Название
